services:
  app:
    image: peng1104/projeto_cloud:v1.0.1
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: